// Generated by the Maven Archetype Plug-in
package osmatrix.app;

import osmatrix.components.Main;

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WORequest;
import com.webobjects.appserver.WODirectAction;

public class DirectAction extends WODirectAction {
	public DirectAction( WORequest request ) {
		super( request );
	}

	public WOActionResults defaultAction() {
		return pageWithName( Main.class.getName() );
	}
}
