// Generated by the Maven Archetype Plug-in
package osmatrix.app;



import com.webobjects.appserver.WOSession;

public class Session extends WOSession {
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
